---
- name: Install Mongo
  hosts: all
  become: true
  tasks:
    - name: Add APT key
      apt_key:
#         url: https://www.mongodb.org/static/pgp/server-5.0.asc
#         state: present
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: Add mongo repository
      apt_repository:
#        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/5.0 multiverse
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        update_cache: yes

    - name: Install Mongo
      apt:
        allow_unauthenticated: yes
        update_cache: yes
        name: mongodb-org
        state: present

    - systemd:
        name: mongod
        enabled: yes
        state: started
